spring.application.name=congestion-tax-calculator
spring.datasource.url=jdbc:postgresql://localhost:5432/congestiontaxes
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=postgres
spring.datasource.password=postgres
server.port=8080