congestion-tax:
  single-charge: 60
  timings:
    - start-time: "06:00"
      end-time: "06:29"
      amount: 8

    - start-time: "06:30"
      end-time: "06:59"
      amount: 13

    - start-time: "07:00"
      end-time: "07:59"
      amount: 18

    - start-time: "08:00"
      end-time: "08:29"
      amount: 13

    - start-time: "08:30"
      end-time: "14:59"
      amount: 8

    - start-time: "15:00"
      end-time: "15:29"
      amount: 13

    - start-time: "15:30"
      end-time: "16:59"
      amount: 18

    - start-time: "17:00"
      end-time: "17:59"
      amount: 13

    - start-time: "18:00"
      end-time: "18:29"
      amount: 8

    - start-time: "18:30"
      end-time: "05:59"
      amount: 0

  exempt-vehicles:
    - Motorcycles
    - Busses
    - Emergency
    - Diplomat
    - Military
    - Foreign

  holidays:
    years:
      - year: 2013
        months:
          - month: 01
            dates:
              - 01

          - month: 03
            dates:
              - 28
              - 29

          - month: 04
            dates:
              - 01
              - 30

          - month: 05
            dates:
              - 01
              - 08
              - 09

          - month: 06
            dates:
              - 05
              - 06
              - 21

          - month: 07
            dates:

          - month: 11
            dates:
              - 01

          - month: 12
            dates:
              - 24
              - 25
              - 26
              - 31


server:
  port: 8181